In [9]:
import torch

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
torch.linspace(1, 17, steps=3)

tensor([ 1.,  9., 17.])

In [14]:
torch.logspace(-10, 10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:

import time
rand1 = torch.rand(100, 100, 100, 100).to(device)
rand2 = torch.rand(100, 100, 100, 100).to(device)


start = time.time()

rand1 @ rand2

end = time.time()

print(f'{end-start:.8f}')

0.14883637


In [23]:
%%time
rand1 = torch.rand(100,100, 100,100).to(device)
rand2 = torch.rand(100,100,100,100).to(device)

x = rand1 @ rand2

CPU times: total: 469 ms
Wall time: 1.4 s


In [24]:
prob = torch.tensor([0.1, 0.9])

In [25]:
prob

tensor([0.1000, 0.9000])

In [27]:
samples = torch.multinomial(prob,num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
x = torch.tensor([1,2,3])
tesnor = torch.cat((x,torch.tensor([3])), dim=0)

In [39]:
tesnor

tensor([1, 2, 3, 3])

In [45]:
torch.tril(torch.rand(3,3))

tensor([[0.7792, 0.0000, 0.0000],
        [0.9910, 0.7106, 0.0000],
        [0.0118, 0.4734, 0.2907]])

In [47]:
torch.triu(torch.ones(4,4))

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

In [54]:
torch.exp(torch.tensor([0]))

tensor([1.])

In [55]:
x = torch.zeros(2,3,4)

In [56]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [64]:
x.transpose(0,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [65]:
a = torch.tensor([1,2,3])
b = torch.tensor([1, 2,3])
c = torch.tensor([1, 2,3])

In [67]:
torch.stack([a,b,c])

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [68]:
import torch.nn as nn

In [84]:
sample = torch.tensor([10.,10.,10.])

lm = nn.Linear(3,3,bias=False)

In [85]:
print(lm(sample))

tensor([-11.5261,   0.9135,  -5.4973], grad_fn=<SqueezeBackward4>)


In [86]:
import torch.nn.functional as F

In [89]:
tesnor1 = torch.tensor([1.0,2.0,3.0])

F.softmax(tesnor1)

C:\Users\SumanPaudel\AppData\Local\Temp\ipykernel_5928\3297064524.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(tesnor1)


tensor([0.0900, 0.2447, 0.6652])

In [97]:
torch.exp(tesnor1) / torch.sum(torch.exp(tesnor1))

tensor([0.0900, 0.2447, 0.6652])

In [100]:
vocab_size = 10000
vector_dim = 100

In [101]:
embedding = nn.Embedding(vocab_size, vector_dim)

In [106]:
embedding(torch.LongTensor([1,3,4,5]))

tensor([[ 1.0968e+00, -4.0924e-01, -2.3089e-01,  9.4508e-01,  9.9422e-01,
          3.9063e-01, -2.7686e-02, -1.1837e+00, -1.1361e-01, -6.1671e-01,
          3.0849e-01,  2.3612e-01, -7.3841e-01,  3.7551e-01,  2.4190e-01,
         -9.8400e-01,  1.2928e+00,  1.4958e+00, -3.9880e-01,  1.7212e+00,
         -4.4725e-01,  7.0387e-01,  4.8873e-01, -1.9324e+00,  2.4552e+00,
          5.1241e-01, -1.1888e+00,  9.4284e-02, -2.5499e-01, -1.3225e+00,
          1.8600e-01, -6.6936e-01,  4.5975e-01, -2.9469e-01,  1.9163e+00,
         -7.9657e-01, -1.3408e+00,  5.6323e-01,  7.1427e-02,  1.6137e+00,
          6.0415e-01,  4.3579e-01,  8.0884e-02, -2.9568e-01,  7.6578e-01,
          1.0005e+00,  2.5799e-01, -1.8353e-01,  6.2589e-02, -8.1081e-02,
         -4.9255e-01, -2.0830e-02, -1.2456e-01,  6.4148e-03,  8.1993e-01,
          1.8179e-01,  1.3259e-01,  7.2159e-01, -5.0773e-01, -3.6228e-02,
         -4.1866e-01, -4.3410e-01, -2.8222e+00,  2.8133e-01, -1.3397e+00,
         -9.3170e-01,  1.1954e+00, -5.