In [1]:
import torch

In [4]:
torch.cuda.get_device_properties(device)

_CudaDeviceProperties(name='NVIDIA GeForce GTX 1650', major=7, minor=5, total_memory=4095MB, multi_processor_count=16)

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [11]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
torch.linspace(1, 17, steps=3)

tensor([ 1.,  9., 17.])

In [14]:
torch.logspace(-10, 10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:

import time
rand1 = torch.rand(100, 100, 100, 100).to(device)
rand2 = torch.rand(100, 100, 100, 100).to(device)


start = time.time()

rand1 @ rand2

end = time.time()

print(f'{end-start:.8f}')

0.14883637


In [23]:
%%time
rand1 = torch.rand(100,100, 100,100).to(device)
rand2 = torch.rand(100,100,100,100).to(device)

x = rand1 @ rand2

CPU times: total: 469 ms
Wall time: 1.4 s


In [24]:
prob = torch.tensor([0.1, 0.9])

In [25]:
prob

tensor([0.1000, 0.9000])

In [27]:
samples = torch.multinomial(prob,num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
x = torch.tensor([1,2,3])
tesnor = torch.cat((x,torch.tensor([3])), dim=0)

In [39]:
tesnor

tensor([1, 2, 3, 3])

In [45]:
torch.tril(torch.rand(3,3))

tensor([[0.7792, 0.0000, 0.0000],
        [0.9910, 0.7106, 0.0000],
        [0.0118, 0.4734, 0.2907]])

In [47]:
torch.triu(torch.ones(4,4))

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

In [54]:
torch.exp(torch.tensor([0]))

tensor([1.])

In [55]:
x = torch.zeros(2,3,4)

In [56]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [64]:
x.transpose(0,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [65]:
a = torch.tensor([1,2,3])
b = torch.tensor([1, 2,3])
c = torch.tensor([1, 2,3])

In [67]:
torch.stack([a,b,c])

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [68]:
import torch.nn as nn

In [84]:
sample = torch.tensor([10.,10.,10.])

lm = nn.Linear(3,3,bias=False)

In [85]:
print(lm(sample))

tensor([-11.5261,   0.9135,  -5.4973], grad_fn=<SqueezeBackward4>)


In [86]:
import torch.nn.functional as F

In [89]:
tesnor1 = torch.tensor([1.0,2.0,3.0])

F.softmax(tesnor1)

C:\Users\SumanPaudel\AppData\Local\Temp\ipykernel_5928\3297064524.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(tesnor1)


tensor([0.0900, 0.2447, 0.6652])

In [97]:
torch.exp(tesnor1) / torch.sum(torch.exp(tesnor1))

tensor([0.0900, 0.2447, 0.6652])

In [107]:
vocab_size = 1000
vector_dim = 100

In [108]:
embedding = nn.Embedding(vocab_size, vector_dim)

In [109]:
embedding(torch.LongTensor([1,3,4,5]))

tensor([[ 1.0029, -0.2383, -1.2281,  0.6995,  1.3561,  0.0992, -0.8799, -1.1418,
         -0.7644, -1.2743,  0.2420, -0.1390, -0.6689,  1.0799, -0.3077, -0.7729,
         -0.2334, -0.2398, -0.8008,  1.1062, -1.2771, -0.6569, -0.6255,  0.5235,
         -0.4018,  0.0392, -0.2078,  0.2449,  1.2342,  1.3092,  1.0960, -0.2186,
         -1.0587, -0.6720, -0.3466,  0.7763, -0.0212,  0.9277, -0.4611, -1.5542,
         -0.4530, -0.1249,  0.0665, -0.7907, -0.4418,  0.2720,  1.3648, -1.1435,
          0.5010, -0.7551, -0.2913, -0.6390,  0.5304, -0.0974, -0.3779, -0.2026,
         -1.5298, -0.1456, -1.2555, -1.1935, -1.5656,  1.0619, -0.2370,  1.6061,
          0.2858, -1.7269, -1.8220,  0.8279,  0.5447,  0.0492, -0.6256, -1.3844,
         -0.6962, -0.5609, -0.5321,  0.4143, -0.9208,  1.2481, -0.6144,  1.0701,
          0.2949, -0.9685,  1.0932,  0.1996, -0.2055,  0.1156,  0.7883,  1.1055,
          0.9496,  0.2062, -0.3972, -0.2724, -0.5258,  0.9084, -0.5501, -0.3903,
         -0.0465,  1.0971,  