In [9]:
import torch

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
torch.linspace(1, 17, steps=3)

tensor([ 1.,  9., 17.])

In [14]:
torch.logspace(-10, 10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:

import time
rand1 = torch.rand(100, 100, 100, 100).to(device)
rand2 = torch.rand(100, 100, 100, 100).to(device)


start = time.time()

rand1 @ rand2

end = time.time()

print(f'{end-start:.8f}')

0.14883637


In [23]:
%%time
rand1 = torch.rand(100,100, 100,100).to(device)
rand2 = torch.rand(100,100,100,100).to(device)

x = rand1 @ rand2

CPU times: total: 469 ms
Wall time: 1.4 s


In [24]:
prob = torch.tensor([0.1, 0.9])

In [25]:
prob

tensor([0.1000, 0.9000])

In [27]:
samples = torch.multinomial(prob,num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
x = torch.tensor([1,2,3])
tesnor = torch.cat((x,torch.tensor([3])), dim=0)

In [39]:
tesnor

tensor([1, 2, 3, 3])

In [45]:
torch.tril(torch.rand(3,3))

tensor([[0.7792, 0.0000, 0.0000],
        [0.9910, 0.7106, 0.0000],
        [0.0118, 0.4734, 0.2907]])

In [47]:
torch.triu(torch.ones(4,4))

tensor([[1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.]])

In [54]:
torch.exp(torch.tensor([0]))

tensor([1.])

In [55]:
x = torch.zeros(2,3,4)

In [56]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [64]:
x.transpose(0,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [65]:
a = torch.tensor([1,2,3])
b = torch.tensor([1, 2,3])
c = torch.tensor([1, 2,3])

In [67]:
torch.stack([a,b,c])

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [68]:
import torch.nn as nn

In [84]:
sample = torch.tensor([10.,10.,10.])

lm = nn.Linear(3,3,bias=False)

In [85]:
print(lm(sample))

tensor([-11.5261,   0.9135,  -5.4973], grad_fn=<SqueezeBackward4>)


In [86]:
import torch.nn.functional as F

In [ ]:
tesnor1 = torch.tensor([1.0,2.0,3.0])