In [9]:
import torch

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
torch.linspace(1, 17, steps=3)

tensor([ 1.,  9., 17.])