In [9]:
import torch

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
torch.linspace(1, 17, steps=3)

tensor([ 1.,  9., 17.])

In [14]:
torch.logspace(-10, 10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:

import time
rand1 = torch.rand(100, 100, 100, 100).to(device)
rand2 = torch.rand(100, 100, 100, 100).to(device)


start = time.time()

rand1 @ rand2

end = time.time()

print(f'{end-start:.8f}')

0.14883637


In [23]:
%%time
rand1 = torch.rand(100,100, 100,100).to(device)
rand2 = torch.rand(100,100,100,100).to(device)

x = rand1 @ rand2

CPU times: total: 469 ms
Wall time: 1.4 s


In [24]:
prob = torch.tensor([0.1, 0.9])

In [25]:
prob

tensor([0.1000, 0.9000])

In [27]:
samples = torch.multinomial(prob,num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
x = torch.tensor([1,2,3])
tesnor = torch.cat((x,torch.tensor([3])), dim=0)

In [39]:
tesnor

tensor([1, 2, 3, 3])